### ISSUE TITLE
Display GeoJSON from backend

### ISSUE THREAD

**Issue by cholin** [KartographischeAktion/aktionskarten-frontend#2]
Features for a given map should be rendered on a leaflet map.

**Comment by cholin** [comment]
url structure for frontend v0.1.0:
* `/`, `/#/` or `/#/maps` : index site with a list of all saved maps
* `/#/maps/<map_name>`: displays map features (in a bounding box see #3)

**Comment by cholin** [comment]
Each feature like polygons, lines or markers should be rendered with the same color.

**Comment by cholin** [comment]
We should use [angular-leaflet-directive](https://github.com/tombatossals/angular-leaflet-directive) for this.

**Comment by cholin** [comment]
For testing we should maybe as well use just a mockup for sample data.

**Comment by cholin** [comment]
We should look as well at https://github.com/mapbox/geojson.io which provides similiar functionality.

**Comment by cholin** [comment]
Another geojson editor seems to be [umap](https://github.com/umap-project/umap/). It's  license seems to be very [open](https://github.com/umap-project/umap/blob/master/LICENSE). For a live demo see [umap.openstreetmap.fr](https://umap.openstreetmap.fr/en/map/new)

**Comment by fupduck** [comment]
we use angular and ui-leaflet
