### ISSUE TITLE
License

### ISSUE THREAD

**Issue by cholin** [KartographischeAktion/aktionskarten-frontend#4]
We should discuss which [FLOSS](https://de.wikipedia.org/wiki/Free/Libre_Open_Source_Software) license like GPL or MIT we want to use.

**Comment by cholin** [comment]
It's already licensed under GPLv2 (see https://github.com/KartographischeAktion/aktionskarten-frontend/blob/master/LICENSE). If everyone is fine with that I think we can close this issue as well as https://github.com/KartographischeAktion/aktionskarten-backend/issues/5.

**Comment by fupduck** [comment]
we stay with GPLv2
